IF NOT EXISTS (SELECT * FROM sys.change_tracking_databases WHERE database_id = DB_ID(N'C:\USERS\ADMIN\DOCUMENTS\HOUSERENTMGTSYSTEM.MDF')) 
   ALTER DATABASE [C:\USERS\ADMIN\DOCUMENTS\HOUSERENTMGTSYSTEM.MDF] 
   SET  CHANGE_TRACKING = ON
GO
